#!/bin/bash
#SBATCH --job-name=time
#SBATCH --output=syn.txt
#SBATCH --error=syn.txt
#SBATCH --ntasks=1
#SBATCH --time=72:00:00
#SBATCH --mem=128G
#SBATCH --gres=gpu:1
#SBATCH -c 8
#SBATCH --partition=gpu_80gb
export PYTHONUNBUFFERED=1
source ~/.bashrc
conda activate gc
python tud.py